// Programmatic 500 Long-Tail Buyer Intent Page Data Registry for LaunchGremlin.com

export const SITE_DOMAIN = 'https://launchgremlin.com';

export const LONG_TAIL_CATEGORIES = [
  'Fitness & Wellness',
  'Food, Dining & Hospitality',
  'Beauty, Style & Personal Care',
  'Creators, Media & Entertainment',
  'Photography & Videography',
  'Medical, Healthcare & Dental',
  'Legal & Professional Services',
  'Real Estate & Property',
  'Construction, Contracting & Trades',
  'Cleaning, Maintenance & Field Services',
  'Startups, SaaS & Tech',
  'Education, E-Learning & Coaching',
  'Events, Weddings & Entertainment',
  'Retail, Fashion & E-Commerce',
  'Automotive & Transportation',
  'Nonprofit, Community & Faith',
  'Financial & Insurance',
  'Home Services & Improvement',
  'B2B Agencies & Marketing',
  'Niche & Specialty Services'
];

// Helper to sanitize title strings into valid slugs
const slugify = (text) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Raw list of 500 long-tail buyer-intent queries categorized into 20 clusters (25 per cluster)
const RAW_QUERIES = [
  // 1. Fitness & Wellness (25)
  { cat: 'Fitness & Wellness', q: 'best website for a gym', label: 'Gyms & Fitness Centers' },
  { cat: 'Fitness & Wellness', q: 'website for yoga studio', label: 'Yoga Studios' },
  { cat: 'Fitness & Wellness', q: 'website for pilates studio', label: 'Pilates Studios' },
  { cat: 'Fitness & Wellness', q: 'crossfit gym website design', label: 'CrossFit Gyms' },
  { cat: 'Fitness & Wellness', q: 'personal trainer booking website', label: 'Personal Trainers' },
  { cat: 'Fitness & Wellness', q: 'martial arts school website', label: 'Martial Arts Schools' },
  { cat: 'Fitness & Wellness', q: 'boxing gym website design', label: 'Boxing Gyms' },
  { cat: 'Fitness & Wellness', q: 'dance studio website design', label: 'Dance Studios' },
  { cat: 'Fitness & Wellness', q: 'spin studio website design', label: 'Spin & Cycling Studios' },
  { cat: 'Fitness & Wellness', q: 'wellness center website design', label: 'Wellness Centers' },
  { cat: 'Fitness & Wellness', q: 'spa and massage website design', label: 'Spas & Massage Therapists' },
  { cat: 'Fitness & Wellness', q: 'med spa website design', label: 'Medical Spas' },
  { cat: 'Fitness & Wellness', q: 'chiropractor website design', label: 'Chiropractors' },
  { cat: 'Fitness & Wellness', q: 'physical therapy website design', label: 'Physical Therapists' },
  { cat: 'Fitness & Wellness', q: 'nutritionist website design', label: 'Nutritionists & Dietitians' },
  { cat: 'Fitness & Wellness', q: 'life coach booking website', label: 'Life Coaches' },
  { cat: 'Fitness & Wellness', q: 'health coach website builder', label: 'Health Coaches' },
  { cat: 'Fitness & Wellness', q: 'bootcamp fitness website', label: 'Fitness Bootcamps' },
  { cat: 'Fitness & Wellness', q: 'bouldering climbing gym website', label: 'Climbing & Bouldering Gyms' },
  { cat: 'Fitness & Wellness', q: 'swimming school website design', label: 'Swim Schools' },
  { cat: 'Fitness & Wellness', q: 'gym membership sales funnel', label: 'Gym Membership Sales' },
  { cat: 'Fitness & Wellness', q: 'boutique fitness studio website', label: 'Boutique Studios' },
  { cat: 'Fitness & Wellness', q: 'athletic performance center website', label: 'Athletic Centers' },
  { cat: 'Fitness & Wellness', q: 'sports academy website design', label: 'Sports Academies' },
  { cat: 'Fitness & Wellness', q: 'holistic health clinic website', label: 'Holistic Health Clinics' },

  // 2. Food, Dining & Hospitality (25)
  { cat: 'Food, Dining & Hospitality', q: 'website for coffee shop', label: 'Coffee Shops' },
  { cat: 'Food, Dining & Hospitality', q: 'restaurant website examples', label: 'Restaurants' },
  { cat: 'Food, Dining & Hospitality', q: 'bakery website design', label: 'Bakeries' },
  { cat: 'Food, Dining & Hospitality', q: 'food truck website builder', label: 'Food Trucks' },
  { cat: 'Food, Dining & Hospitality', q: 'catering company website design', label: 'Catering Companies' },
  { cat: 'Food, Dining & Hospitality', q: 'cocktail bar website design', label: 'Cocktail Bars' },
  { cat: 'Food, Dining & Hospitality', q: 'brewery website design', label: 'Craft Breweries' },
  { cat: 'Food, Dining & Hospitality', q: 'winery website design', label: 'Wineries & Vineyards' },
  { cat: 'Food, Dining & Hospitality', q: 'pizzeria website design', label: 'Pizzerias' },
  { cat: 'Food, Dining & Hospitality', q: 'sushi restaurant website', label: 'Sushi Restaurants' },
  { cat: 'Food, Dining & Hospitality', q: 'fine dining restaurant website', label: 'Fine Dining Eateries' },
  { cat: 'Food, Dining & Hospitality', q: 'fast casual restaurant website', label: 'Fast Casual Dining' },
  { cat: 'Food, Dining & Hospitality', q: 'bistro cafe website design', label: 'Bistros & Cafes' },
  { cat: 'Food, Dining & Hospitality', q: 'ice cream shop website', label: 'Ice Cream Shops' },
  { cat: 'Food, Dining & Hospitality', q: 'juice bar website design', label: 'Juice & Smoothie Bars' },
  { cat: 'Food, Dining & Hospitality', q: 'meal prep delivery website', label: 'Meal Prep Services' },
  { cat: 'Food, Dining & Hospitality', q: 'private chef website design', label: 'Private Chefs' },
  { cat: 'Food, Dining & Hospitality', q: 'ghost kitchen website design', label: 'Ghost Kitchens' },
  { cat: 'Food, Dining & Hospitality', q: 'hotel boutique website design', label: 'Boutique Hotels' },
  { cat: 'Food, Dining & Hospitality', q: 'bed and breakfast website', label: 'Bed & Breakfasts' },
  { cat: 'Food, Dining & Hospitality', q: 'event venue website design', label: 'Event Venues' },
  { cat: 'Food, Dining & Hospitality', q: 'nightclub lounge website', label: 'Nightclubs & Lounges' },
  { cat: 'Food, Dining & Hospitality', q: 'steakhouse website design', label: 'Steakhouses' },
  { cat: 'Food, Dining & Hospitality', q: 'seafood restaurant website', label: 'Seafood Restaurants' },
  { cat: 'Food, Dining & Hospitality', q: 'vegan restaurant website', label: 'Vegan Restaurants' },

  // 3. Beauty, Style & Personal Care (25)
  { cat: 'Beauty, Style & Personal Care', q: 'website for makeup artist', label: 'Makeup Artists' },
  { cat: 'Beauty, Style & Personal Care', q: 'hair salon booking website', label: 'Hair Salons' },
  { cat: 'Beauty, Style & Personal Care', q: 'barbershop appointment website', label: 'Barbershops' },
  { cat: 'Beauty, Style & Personal Care', q: 'nail salon website design', label: 'Nail Salons' },
  { cat: 'Beauty, Style & Personal Care', q: 'lash and brow studio website', label: 'Lash & Brow Studios' },
  { cat: 'Beauty, Style & Personal Care', q: 'tattoo parlor website design', label: 'Tattoo Studios' },
  { cat: 'Beauty, Style & Personal Care', q: 'piercing studio website', label: 'Body Piercing Studios' },
  { cat: 'Beauty, Style & Personal Care', q: 'esthetician website design', label: 'Estheticians' },
  { cat: 'Beauty, Style & Personal Care', q: 'tanning salon website', label: 'Tanning Salons' },
  { cat: 'Beauty, Style & Personal Care', q: 'skincare clinic website design', label: 'Skincare Clinics' },
  { cat: 'Beauty, Style & Personal Care', q: 'microblading studio website', label: 'Microblading Artists' },
  { cat: 'Beauty, Style & Personal Care', q: 'bridal hair makeup website', label: 'Bridal Stylists' },
  { cat: 'Beauty, Style & Personal Care', q: 'mobile barber website', label: 'Mobile Barbers' },
  { cat: 'Beauty, Style & Personal Care', q: 'men grooming lounge website', label: 'Men\'s Grooming Lounges' },
  { cat: 'Beauty, Style & Personal Care', q: 'hair extensions salon website', label: 'Hair Extension Studios' },
  { cat: 'Beauty, Style & Personal Care', q: 'cosmetic injector website', label: 'Cosmetic Injectors' },
  { cat: 'Beauty, Style & Personal Care', q: 'permanent makeup website', label: 'Permanent Makeup Artists' },
  { cat: 'Beauty, Style & Personal Care', q: 'waxing salon website design', label: 'Waxing Salons' },
  { cat: 'Beauty, Style & Personal Care', q: 'beauty school website design', label: 'Beauty Academies' },
  { cat: 'Beauty, Style & Personal Care', q: 'hairstylist portfolio website', label: 'Hairstylists' },
  { cat: 'Beauty, Style & Personal Care', q: 'freelance makeup artist website', label: 'Freelance Makeup Artists' },
  { cat: 'Beauty, Style & Personal Care', q: 'luxury spa website design', label: 'Day Spas' },
  { cat: 'Beauty, Style & Personal Care', q: 'barber chair booking funnel', label: 'Barber Chairs' },
  { cat: 'Beauty, Style & Personal Care', q: 'salon suite website design', label: 'Salon Suites' },
  { cat: 'Beauty, Style & Personal Care', q: 'organic beauty spa website', label: 'Organic Beauty Spas' },

  // 4. Creators, Media & Entertainment (25)
  { cat: 'Creators, Media & Entertainment', q: 'creator website examples', label: 'Content Creators' },
  { cat: 'Creators, Media & Entertainment', q: 'website for podcast', label: 'Podcasters' },
  { cat: 'Creators, Media & Entertainment', q: 'website for dj', label: 'DJs & Music Artists' },
  { cat: 'Creators, Media & Entertainment', q: 'website for musician', label: 'Musicians & Bands' },
  { cat: 'Creators, Media & Entertainment', q: 'youtuber website builder', label: 'YouTubers' },
  { cat: 'Creators, Media & Entertainment', q: 'streamer twitch website', label: 'Twitch Streamers' },
  { cat: 'Creators, Media & Entertainment', q: 'author book launch website', label: 'Authors & Writers' },
  { cat: 'Creators, Media & Entertainment', q: 'voice actor portfolio website', label: 'Voice Actors' },
  { cat: 'Creators, Media & Entertainment', q: 'actor headshot website', label: 'Actors & Performers' },
  { cat: 'Creators, Media & Entertainment', q: 'comedian tour website', label: 'Comedians' },
  { cat: 'Creators, Media & Entertainment', q: 'film director portfolio website', label: 'Film Directors' },
  { cat: 'Creators, Media & Entertainment', q: 'music producer website', label: 'Music Producers' },
  { cat: 'Creators, Media & Entertainment', q: 'record label website design', label: 'Record Labels' },
  { cat: 'Creators, Media & Entertainment', q: 'podcast network website', label: 'Podcast Networks' },
  { cat: 'Creators, Media & Entertainment', q: 'newsletter creator website', label: 'Newsletter Writers' },
  { cat: 'Creators, Media & Entertainment', q: 'substack beehiiv custom website', label: 'Substack & Beehiiv Creators' },
  { cat: 'Creators, Media & Entertainment', q: 'link in bio replacement website', label: 'Link-in-Bio Websites' },
  { cat: 'Creators, Media & Entertainment', q: 'digital artist portfolio website', label: 'Digital Artists' },
  { cat: 'Creators, Media & Entertainment', q: 'animator portfolio website', label: 'Animators & 3D Artists' },
  { cat: 'Creators, Media & Entertainment', q: 'event dj booking website', label: 'Event & Club DJs' },
  { cat: 'Creators, Media & Entertainment', q: 'wedding band website design', label: 'Wedding Bands' },
  { cat: 'Creators, Media & Entertainment', q: 'indie game developer website', label: 'Indie Game Developers' },
  { cat: 'Creators, Media & Entertainment', q: 'content creator media kit website', label: 'Creator Media Kits' },
  { cat: 'Creators, Media & Entertainment', q: 'influencer brand deal website', label: 'Influencer Brand Deals' },
  { cat: 'Creators, Media & Entertainment', q: 'creative agency portfolio website', label: 'Creative Studios' },

  // 5. Photography & Videography (25)
  { cat: 'Photography & Videography', q: 'wedding photographer website design', label: 'Wedding Photographers' },
  { cat: 'Photography & Videography', q: 'portrait photographer website', label: 'Portrait Photographers' },
  { cat: 'Photography & Videography', q: 'commercial photographer website', label: 'Commercial Photographers' },
  { cat: 'Photography & Videography', q: 'real estate photographer website', label: 'Real Estate Photographers' },
  { cat: 'Photography & Videography', q: 'drone videographer website', label: 'Drone & Aerial Videographers' },
  { cat: 'Photography & Videography', q: 'event photographer website', label: 'Event Photographers' },
  { cat: 'Photography & Videography', q: 'family photographer website', label: 'Family Photographers' },
  { cat: 'Photography & Videography', q: 'newborn photographer website', label: 'Newborn Photographers' },
  { cat: 'Photography & Videography', q: 'boudoir photographer website', label: 'Boudoir Photographers' },
  { cat: 'Photography & Videography', q: 'fashion photographer website', label: 'Fashion Photographers' },
  { cat: 'Photography & Videography', q: 'headshot photographer website', label: 'Headshot Photographers' },
  { cat: 'Photography & Videography', q: 'sports photographer website', label: 'Sports Photographers' },
  { cat: 'Photography & Videography', q: 'nature wildlife photographer website', label: 'Nature Photographers' },
  { cat: 'Photography & Videography', q: 'food photographer website', label: 'Food Photographers' },
  { cat: 'Photography & Videography', q: 'product photographer website', label: 'Product Photographers' },
  { cat: 'Photography & Videography', q: 'music video director website', label: 'Music Video Directors' },
  { cat: 'Photography & Videography', q: 'documentary filmmaker website', label: 'Documentary Filmmakers' },
  { cat: 'Photography & Videography', q: 'videography booking website', label: 'Videographers' },
  { cat: 'Photography & Videography', q: 'photo booth rental website', label: 'Photo Booth Companies' },
  { cat: 'Photography & Videography', q: 'studio rental website design', label: 'Photo Studios' },
  { cat: 'Photography & Videography', q: 'underwater photographer website', label: 'Underwater Photographers' },
  { cat: 'Photography & Videography', q: 'landscape photographer website', label: 'Landscape Photographers' },
  { cat: 'Photography & Videography', q: 'travel photographer website', label: 'Travel Photographers' },
  { cat: 'Photography & Videography', q: 'architecture photographer website', label: 'Architectural Photographers' },
  { cat: 'Photography & Videography', q: 'car automotive photographer website', label: 'Automotive Photographers' },

  // 6. Medical, Healthcare & Dental (25)
  { cat: 'Medical, Healthcare & Dental', q: 'cosmetic dentist website design', label: 'Cosmetic Dentists' },
  { cat: 'Medical, Healthcare & Dental', q: 'orthodontist practice website', label: 'Orthodontists' },
  { cat: 'Medical, Healthcare & Dental', q: 'pediatric dentist website', label: 'Pediatric Dentists' },
  { cat: 'Medical, Healthcare & Dental', q: 'dermatology clinic website', label: 'Dermatology Clinics' },
  { cat: 'Medical, Healthcare & Dental', q: 'plastic surgeon website design', label: 'Plastic Surgeons' },
  { cat: 'Medical, Healthcare & Dental', q: 'chiropractic clinic website', label: 'Chiropractic Clinics' },
  { cat: 'Medical, Healthcare & Dental', q: 'optometrist eye care website', label: 'Optometrists' },
  { cat: 'Medical, Healthcare & Dental', q: 'podiatrist foot clinic website', label: 'Podiatrists' },
  { cat: 'Medical, Healthcare & Dental', q: 'psychologist therapist website', label: 'Psychologists' },
  { cat: 'Medical, Healthcare & Dental', q: 'mental health counseling website', label: 'Therapists & Counselors' },
  { cat: 'Medical, Healthcare & Dental', q: 'veterinary clinic website', label: 'Veterinary Clinics' },
  { cat: 'Medical, Healthcare & Dental', q: 'pet hospital website design', label: 'Animal Hospitals' },
  { cat: 'Medical, Healthcare & Dental', q: 'urgent care clinic website', label: 'Urgent Care Clinics' },
  { cat: 'Medical, Healthcare & Dental', q: 'telehealth medical website', label: 'Telehealth Practices' },
  { cat: 'Medical, Healthcare & Dental', q: 'physical rehab clinic website', label: 'Rehab Clinics' },
  { cat: 'Medical, Healthcare & Dental', q: 'fertility clinic website', label: 'Fertility Clinics' },
  { cat: 'Medical, Healthcare & Dental', q: 'cardiology practice website', label: 'Cardiologists' },
  { cat: 'Medical, Healthcare & Dental', q: 'orthopedic surgeon website', label: 'Orthopedic Surgeons' },
  { cat: 'Medical, Healthcare & Dental', q: 'holistic medicine website', label: 'Holistic Doctors' },
  { cat: 'Medical, Healthcare & Dental', q: 'acupuncturist website design', label: 'Acupuncturists' },
  { cat: 'Medical, Healthcare & Dental', q: 'dental implant specialist website', label: 'Dental Implant Specialists' },
  { cat: 'Medical, Healthcare & Dental', q: 'teeth whitening clinic website', label: 'Teeth Whitening Clinics' },
  { cat: 'Medical, Healthcare & Dental', q: 'home health care website', label: 'Home Health Care' },
  { cat: 'Medical, Healthcare & Dental', q: 'senior living facility website', label: 'Senior Living Centers' },
  { cat: 'Medical, Healthcare & Dental', q: 'medical spa booking website', label: 'Medical Spas' },

  // 7. Legal & Professional Services (25)
  { cat: 'Legal & Professional Services', q: 'personal injury lawyer website', label: 'Personal Injury Lawyers' },
  { cat: 'Legal & Professional Services', q: 'family law attorney website', label: 'Family Law Attorneys' },
  { cat: 'Legal & Professional Services', q: 'criminal defense lawyer website', label: 'Criminal Defense Lawyers' },
  { cat: 'Legal & Professional Services', q: 'corporate law firm website', label: 'Corporate Law Firms' },
  { cat: 'Legal & Professional Services', q: 'estate planning attorney website', label: 'Estate Planning Lawyers' },
  { cat: 'Legal & Professional Services', q: 'immigration lawyer website', label: 'Immigration Lawyers' },
  { cat: 'Legal & Professional Services', q: 'tax attorney website design', label: 'Tax Attorneys' },
  { cat: 'Legal & Professional Services', q: 'real estate lawyer website', label: 'Real Estate Lawyers' },
  { cat: 'Legal & Professional Services', q: 'employment law firm website', label: 'Employment Lawyers' },
  { cat: 'Legal & Professional Services', q: 'bankruptcy lawyer website', label: 'Bankruptcy Lawyers' },
  { cat: 'Legal & Professional Services', q: 'intellectual property lawyer website', label: 'IP Lawyers' },
  { cat: 'Legal & Professional Services', q: 'solo practitioner attorney website', label: 'Solo Attorneys' },
  { cat: 'Legal & Professional Services', q: 'cpa firm website design', label: 'CPA Firms' },
  { cat: 'Legal & Professional Services', q: 'bookkeeping service website', label: 'Bookkeepers' },
  { cat: 'Legal & Professional Services', q: 'tax preparation website', label: 'Tax Professionals' },
  { cat: 'Legal & Professional Services', q: 'fractional cfo website', label: 'Fractional CFOs' },
  { cat: 'Legal & Professional Services', q: 'financial advisor website', label: 'Financial Advisors' },
  { cat: 'Legal & Professional Services', q: 'wealth management firm website', label: 'Wealth Management Firms' },
  { cat: 'Legal & Professional Services', q: 'notary public website design', label: 'Notaries Public' },
  { cat: 'Legal & Professional Services', q: 'business consultant website', label: 'Business Consultants' },
  { cat: 'Legal & Professional Services', q: 'management consulting website', label: 'Management Consultants' },
  { cat: 'Legal & Professional Services', q: 'hr consultant website design', label: 'HR Consultants' },
  { cat: 'Legal & Professional Services', q: 'recruitment agency website', label: 'Recruitment Agencies' },
  { cat: 'Legal & Professional Services', q: 'private investigator website', label: 'Private Investigators' },
  { cat: 'Legal & Professional Services', q: 'translator interpreter website', label: 'Translators & Interpreters' },

  // 8. Real Estate & Property (25)
  { cat: 'Real Estate & Property', q: 'realtor website with idx', label: 'Realtors with IDX' },
  { cat: 'Real Estate & Property', q: 'luxury real estate website', label: 'Luxury Real Estate Agents' },
  { cat: 'Real Estate & Property', q: 'commercial real estate broker website', label: 'Commercial Brokers' },
  { cat: 'Real Estate & Property', q: 'property management company website', label: 'Property Managers' },
  { cat: 'Real Estate & Property', q: 'home builder website design', label: 'Custom Home Builders' },
  { cat: 'Real Estate & Property', q: 'mortgage broker website design', label: 'Mortgage Brokers' },
  { cat: 'Real Estate & Property', q: 'home inspector website', label: 'Home Inspectors' },
  { cat: 'Real Estate & Property', q: 'real estate team website', label: 'Real Estate Teams' },
  { cat: 'Real Estate & Property', q: 'apartment complex website', label: 'Apartment Complexes' },
  { cat: 'Real Estate & Property', q: 'vacation rental airbnb website', label: 'Airbnb & Vacation Rentals' },
  { cat: 'Real Estate & Property', q: 'land developer website design', label: 'Land Developers' },
  { cat: 'Real Estate & Property', q: 'title company website design', label: 'Title Companies' },
  { cat: 'Real Estate & Property', q: 'escrow service website', label: 'Escrow Services' },
  { cat: 'Real Estate & Property', q: 'interior designer portfolio website', label: 'Interior Designers' },
  { cat: 'Real Estate & Property', q: 'architect firm website design', label: 'Architects' },
  { cat: 'Real Estate & Property', q: 'landscape architect website', label: 'Landscape Architects' },
  { cat: 'Real Estate & Property', q: 'home staging company website', label: 'Home Stagers' },
  { cat: 'Real Estate & Property', q: 'appraiser real estate website', label: 'Real Estate Appraisers' },
  { cat: 'Real Estate & Property', q: 'home valuation lead website', label: 'Home Valuation Leads' },
  { cat: 'Real Estate & Property', q: 'custom home contractor website', label: 'Custom Home Contractors' },
  { cat: 'Real Estate & Property', q: 'roofing contractor website', label: 'Roofing Contractors' },
  { cat: 'Real Estate & Property', q: 'solar panel installer website', label: 'Solar Installers' },
  { cat: 'Real Estate & Property', q: 'hvac contractor website', label: 'HVAC Companies' },
  { cat: 'Real Estate & Property', q: 'plumbing company website', label: 'Plumbers' },
  { cat: 'Real Estate & Property', q: 'electrician business website', label: 'Electricians' },

  // 9. Construction, Contracting & Trades (25)
  { cat: 'Construction, Contracting & Trades', q: 'general contractor website design', label: 'General Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'commercial construction website', label: 'Commercial Construction' },
  { cat: 'Construction, Contracting & Trades', q: 'remodeling contractor website', label: 'Remodeling Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'kitchen bath remodeler website', label: 'Kitchen & Bath Remodelers' },
  { cat: 'Construction, Contracting & Trades', q: 'deck patio builder website', label: 'Deck & Patio Builders' },
  { cat: 'Construction, Contracting & Trades', q: 'painting contractor website', label: 'Painting Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'flooring company website', label: 'Flooring Companies' },
  { cat: 'Construction, Contracting & Trades', q: 'drywall plaster contractor website', label: 'Drywall Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'masonry bricklayer website', label: 'Masonry Masons' },
  { cat: 'Construction, Contracting & Trades', q: 'fencing contractor website', label: 'Fence Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'landscaping company website', label: 'Landscapers' },
  { cat: 'Construction, Contracting & Trades', q: 'tree service company website', label: 'Tree Services' },
  { cat: 'Construction, Contracting & Trades', q: 'pest control company website', label: 'Pest Control Companies' },
  { cat: 'Construction, Contracting & Trades', q: 'pool builder website design', label: 'Pool Builders' },
  { cat: 'Construction, Contracting & Trades', q: 'garage door repair website', label: 'Garage Door Technicians' },
  { cat: 'Construction, Contracting & Trades', q: 'window door installer website', label: 'Window & Door Installers' },
  { cat: 'Construction, Contracting & Trades', q: 'insulation contractor website', label: 'Insulation Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'paving asphalt contractor website', label: 'Paving Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'demolition company website', label: 'Demolition Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'excavation contractor website', label: 'Excavation Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'scaffolding rental website', label: 'Scaffolding Companies' },
  { cat: 'Construction, Contracting & Trades', q: 'commercial roofer website', label: 'Commercial Roofers' },
  { cat: 'Construction, Contracting & Trades', q: 'waterproofing contractor website', label: 'Waterproofing Contractors' },
  { cat: 'Construction, Contracting & Trades', q: 'handyman service website', label: 'Handyman Services' },
  { cat: 'Construction, Contracting & Trades', q: 'concrete contractor website', label: 'Concrete Contractors' },

  // 10. Cleaning, Maintenance & Field Services (25)
  { cat: 'Cleaning, Maintenance & Field Services', q: 'house cleaning company website', label: 'House Cleaners' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'commercial janitorial website', label: 'Commercial Janitorial' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'maid service booking website', label: 'Maid Services' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'carpet cleaning website design', label: 'Carpet Cleaners' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'window cleaning website', label: 'Window Cleaners' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'pressure washing website design', label: 'Pressure Washers' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'junk removal website design', label: 'Junk Removal Services' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'auto detailing website design', label: 'Auto Detailers' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'mobile car wash website', label: 'Mobile Car Washes' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'chimney sweep website', label: 'Chimney Sweeps' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'gutter cleaning website', label: 'Gutter Cleaners' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'pool cleaning service website', label: 'Pool Cleaners' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'laundry dry cleaning website', label: 'Dry Cleaners' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'appliance repair website', label: 'Appliance Repair' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'locksmith service website', label: 'Locksmiths' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'towing company website design', label: 'Towing Companies' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'septic tank service website', label: 'Septic Services' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'duct cleaning company website', label: 'Air Duct Cleaners' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'mold remediation website', label: 'Mold Remediation' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'disaster restoration website', label: 'Disaster Restoration' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'dog walking pet sitting website', label: 'Pet Sitters' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'dog grooming salon website', label: 'Pet Groomers' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'mobile pet groomer website', label: 'Mobile Groomers' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'lawn care service website', label: 'Lawn Care' },
  { cat: 'Cleaning, Maintenance & Field Services', q: 'snow removal service website', label: 'Snow Removal' },

  // 11. Startups, SaaS & Tech (25)
  { cat: 'Startups, SaaS & Tech', q: 'website for startup', label: 'Tech Startups' },
  { cat: 'Startups, SaaS & Tech', q: 'affordable business website', label: 'Affordable Business Sites' },
  { cat: 'Startups, SaaS & Tech', q: 'ai saas landing page design', label: 'AI SaaS Platforms' },
  { cat: 'Startups, SaaS & Tech', q: 'b2b software website builder', label: 'B2B Software' },
  { cat: 'Startups, SaaS & Tech', q: 'mobile app landing page design', label: 'Mobile App Launches' },
  { cat: 'Startups, SaaS & Tech', q: 'fintech startup website design', label: 'FinTech Startups' },
  { cat: 'Startups, SaaS & Tech', q: 'healthtech startup website', label: 'HealthTech Startups' },
  { cat: 'Startups, SaaS & Tech', q: 'edtech platform website', label: 'EdTech Platforms' },
  { cat: 'Startups, SaaS & Tech', q: 'web3 crypto project website', label: 'Web3 & Crypto' },
  { cat: 'Startups, SaaS & Tech', q: 'cybersecurity company website', label: 'Cybersecurity Firms' },
  { cat: 'Startups, SaaS & Tech', q: 'cloud software website design', label: 'Cloud SaaS' },
  { cat: 'Startups, SaaS & Tech', q: 'devops consulting website', label: 'DevOps Consultants' },
  { cat: 'Startups, SaaS & Tech', q: 'no code agency website', label: 'No-Code Studios' },
  { cat: 'Startups, SaaS & Tech', q: 'data analytics firm website', label: 'Data Analytics Firms' },
  { cat: 'Startups, SaaS & Tech', q: 'iot hardware startup website', label: 'IoT Hardware Startups' },
  { cat: 'Startups, SaaS & Tech', q: 'ecommerce saas website design', label: 'E-Commerce SaaS' },
  { cat: 'Startups, SaaS & Tech', q: 'marketplace platform website', label: 'Two-Sided Marketplaces' },
  { cat: 'Startups, SaaS & Tech', q: 'insurtech startup website', label: 'InsurTech Startups' },
  { cat: 'Startups, SaaS & Tech', q: 'cleantech green energy website', label: 'CleanTech Startups' },
  { cat: 'Startups, SaaS & Tech', q: 'proptech real estate saas website', label: 'PropTech SaaS' },
  { cat: 'Startups, SaaS & Tech', q: 'hrtech recruitment software website', label: 'HRTech Software' },
  { cat: 'Startups, SaaS & Tech', q: 'martech marketing tool website', label: 'MarTech Software' },
  { cat: 'Startups, SaaS & Tech', q: 'api developer platform website', label: 'Developer APIs' },
  { cat: 'Startups, SaaS & Tech', q: 'micro saas landing page', label: 'Micro-SaaS Products' },
  { cat: 'Startups, SaaS & Tech', q: 'bootstrapped software website', label: 'Bootstrapped SaaS' },

  // 12. Education, E-Learning & Coaching (25)
  { cat: 'Education, E-Learning & Coaching', q: 'online course creator website', label: 'Course Creators' },
  { cat: 'Education, E-Learning & Coaching', q: 'tutor tutoring center website', label: 'Tutoring Centers' },
  { cat: 'Education, E-Learning & Coaching', q: 'language school website design', label: 'Language Schools' },
  { cat: 'Education, E-Learning & Coaching', q: 'music teacher website design', label: 'Music Teachers' },
  { cat: 'Education, E-Learning & Coaching', q: 'driving school website design', label: 'Driving Schools' },
  { cat: 'Education, E-Learning & Coaching', q: 'flight school website design', label: 'Flight Academies' },
  { cat: 'Education, E-Learning & Coaching', q: 'coding bootcamp website design', label: 'Coding Bootcamps' },
  { cat: 'Education, E-Learning & Coaching', q: 'cooking class studio website', label: 'Cooking Schools' },
  { cat: 'Education, E-Learning & Coaching', q: 'art school workshop website', label: 'Art Schools' },
  { cat: 'Education, E-Learning & Coaching', q: 'acting school workshop website', label: 'Acting Studios' },
  { cat: 'Education, E-Learning & Coaching', q: 'montessori preschool website', label: 'Montessori Schools' },
  { cat: 'Education, E-Learning & Coaching', q: 'daycare childcare website', label: 'Daycare Centers' },
  { cat: 'Education, E-Learning & Coaching', q: 'private k12 school website', label: 'Private K-12 Schools' },
  { cat: 'Education, E-Learning & Coaching', q: 'test prep coaching website', label: 'Test Prep Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'career coach website design', label: 'Career Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'relationship marriage coach website', label: 'Relationship Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'financial coach website design', label: 'Financial Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'sales coach trainer website', label: 'Sales Trainers' },
  { cat: 'Education, E-Learning & Coaching', q: 'mindset manifestation coach website', label: 'Mindset Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'parenting coach website', label: 'Parenting Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'public speaking coach website', label: 'Public Speaking Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'voice singing coach website', label: 'Vocal Coaches' },
  { cat: 'Education, E-Learning & Coaching', q: 'fitness certifications website', label: 'Fitness Certifications' },
  { cat: 'Education, E-Learning & Coaching', q: 'corporate trainer website', label: 'Corporate Trainers' },
  { cat: 'Education, E-Learning & Coaching', q: 'mastermind group website', label: 'Masterminds' },

  // 13. Events, Weddings & Entertainment (25)
  { cat: 'Events, Weddings & Entertainment', q: 'wedding planner website design', label: 'Wedding Planners' },
  { cat: 'Events, Weddings & Entertainment', q: 'event planner agency website', label: 'Event Planners' },
  { cat: 'Events, Weddings & Entertainment', q: 'florist flower shop website', label: 'Florists' },
  { cat: 'Events, Weddings & Entertainment', q: 'catering service booking website', label: 'Event Caterers' },
  { cat: 'Events, Weddings & Entertainment', q: 'wedding venue website design', label: 'Wedding Venues' },
  { cat: 'Events, Weddings & Entertainment', q: 'photo booth rental company website', label: 'Photo Booth Rentals' },
  { cat: 'Events, Weddings & Entertainment', q: 'party rental company website', label: 'Party Rentals' },
  { cat: 'Events, Weddings & Entertainment', q: 'magician illusionist website', label: 'Magicians' },
  { cat: 'Events, Weddings & Entertainment', q: 'live band booking website', label: 'Live Bands' },
  { cat: 'Events, Weddings & Entertainment', q: 'corporate event agency website', label: 'Corporate Event Agencies' },
  { cat: 'Events, Weddings & Entertainment', q: 'baking cake designer website', label: 'Custom Cake Designers' },
  { cat: 'Events, Weddings & Entertainment', q: 'bridal boutique website design', label: 'Bridal Boutiques' },
  { cat: 'Events, Weddings & Entertainment', q: 'tuxedo suit rental website', label: 'Tuxedo Rentals' },
  { cat: 'Events, Weddings & Entertainment', q: 'limo party bus rental website', label: 'Party Buses' },
  { cat: 'Events, Weddings & Entertainment', q: 'destination wedding website', label: 'Destination Weddings' },
  { cat: 'Events, Weddings & Entertainment', q: 'videographer wedding website', label: 'Wedding Videographers' },
  { cat: 'Events, Weddings & Entertainment', q: 'dj lighting service website', label: 'Event DJs & Lighting' },
  { cat: 'Events, Weddings & Entertainment', q: 'balloon decor artist website', label: 'Balloon Stylists' },
  { cat: 'Events, Weddings & Entertainment', q: 'charcuterie catering website', label: 'Charcuterie Caterers' },
  { cat: 'Events, Weddings & Entertainment', q: 'cocktail bartender rental website', label: 'Mobile Bartenders' },
  { cat: 'Events, Weddings & Entertainment', q: 'kids party entertainment website', label: 'Kids Entertainers' },
  { cat: 'Events, Weddings & Entertainment', q: 'escape room website design', label: 'Escape Rooms' },
  { cat: 'Events, Weddings & Entertainment', q: 'axe throwing venue website', label: 'Axe Throwing Venues' },
  { cat: 'Events, Weddings & Entertainment', q: 'arcade bowling alley website', label: 'Bowling Alleys' },
  { cat: 'Events, Weddings & Entertainment', q: 'comedy club website design', label: 'Comedy Clubs' },

  // 14. Retail, Fashion & E-Commerce (25)
  { cat: 'Retail, Fashion & E-Commerce', q: 'clothing boutique website design', label: 'Clothing Boutiques' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'jewelry store website design', label: 'Jewelry Stores' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'vintage thrift shop website', label: 'Vintage Shops' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'shoe store website design', label: 'Shoe Retailers' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'streetwear brand website', label: 'Streetwear Brands' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'activewear fitness brand website', label: 'Activewear Brands' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'swimwear brand website design', label: 'Swimwear Brands' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'handbag leather goods website', label: 'Leather Goods' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'luxury watches jeweler website', label: 'Watch Jewelers' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'eyewear sunglasses brand website', label: 'Eyewear Brands' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'home decor store website', label: 'Home Decor Stores' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'furniture store website design', label: 'Furniture Stores' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'candle fragrance shop website', label: 'Candle & Fragrance Shops' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'cosmetics beauty brand website', label: 'Beauty Brands' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'pet supplies store website', label: 'Pet Supply Shops' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'plant nursery flower website', label: 'Plant Nurseries' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'bookstore indie shop website', label: 'Indie Bookstores' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'toy game store website', label: 'Toy Stores' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'sports goods shop website', label: 'Sporting Goods Stores' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'bicycle bike shop website', label: 'Bike Shops' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'cbd wellness shop website', label: 'CBD & Wellness Shops' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'art gallery store website', label: 'Art Galleries' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'craft supply store website', label: 'Craft Supply Shops' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'organic grocery store website', label: 'Organic Grocers' },
  { cat: 'Retail, Fashion & E-Commerce', q: 'gourmet food gift basket website', label: 'Gourmet Gift Shops' },

  // 15. Automotive & Transportation (25)
  { cat: 'Automotive & Transportation', q: 'auto repair shop website', label: 'Auto Repair Shops' },
  { cat: 'Automotive & Transportation', q: 'car dealership website design', label: 'Car Dealerships' },
  { cat: 'Automotive & Transportation', q: 'used car lot website', label: 'Used Car Lots' },
  { cat: 'Automotive & Transportation', q: 'motorcycle dealership website', label: 'Motorcycle Shops' },
  { cat: 'Automotive & Transportation', q: 'boat yacht charter website', label: 'Yacht Charters' },
  { cat: 'Automotive & Transportation', q: 'car rental agency website', label: 'Car Rental Agencies' },
  { cat: 'Automotive & Transportation', q: 'limousine service website', label: 'Limo Services' },
  { cat: 'Automotive & Transportation', q: 'trucking logistics company website', label: 'Trucking Companies' },
  { cat: 'Automotive & Transportation', q: 'freight brokerage website', label: 'Freight Brokers' },
  { cat: 'Automotive & Transportation', q: 'courier delivery service website', label: 'Courier Services' },
  { cat: 'Automotive & Transportation', q: 'rv camper rental website', label: 'RV & Camper Rentals' },
  { cat: 'Automotive & Transportation', q: 'auto body paint shop website', label: 'Auto Body Shops' },
  { cat: 'Automotive & Transportation', q: 'tire wheel shop website', label: 'Tire & Wheel Shops' },
  { cat: 'Automotive & Transportation', q: 'car wrap window tint website', label: 'Car Wrap & Tint Shops' },
  { cat: 'Automotive & Transportation', q: 'mobile oil change website', label: 'Mobile Oil Change' },
  { cat: 'Automotive & Transportation', q: 'towing roadside assistance website', label: 'Towing Services' },
  { cat: 'Automotive & Transportation', q: 'parking garage valet website', label: 'Valet Services' },
  { cat: 'Automotive & Transportation', q: 'private jet charter website', label: 'Private Jet Charters' },
  { cat: 'Automotive & Transportation', q: 'aviation flight charter website', label: 'Flight Charters' },
  { cat: 'Automotive & Transportation', q: 'moving company website design', label: 'Moving Companies' },
  { cat: 'Automotive & Transportation', q: 'storage facility website design', label: 'Storage Facilities' },
  { cat: 'Automotive & Transportation', q: 'auto parts store website', label: 'Auto Parts Stores' },
  { cat: 'Automotive & Transportation', q: 'electric vehicle charging website', label: 'EV Charging Networks' },
  { cat: 'Automotive & Transportation', q: 'fleet management website', label: 'Fleet Management' },
  { cat: 'Automotive & Transportation', q: 'marina boat slip website', label: 'Marinas' },

  // 16. Nonprofit, Community & Faith (25)
  { cat: 'Nonprofit, Community & Faith', q: 'nonprofit organization website', label: 'Nonprofit Organizations' },
  { cat: 'Nonprofit, Community & Faith', q: 'charity foundation website design', label: 'Charity Foundations' },
  { cat: 'Nonprofit, Community & Faith', q: 'church religious organization website', label: 'Churches & Places of Worship' },
  { cat: 'Nonprofit, Community & Faith', q: 'animal shelter rescue website', label: 'Animal Shelters' },
  { cat: 'Nonprofit, Community & Faith', q: 'community center website', label: 'Community Centers' },
  { cat: 'Nonprofit, Community & Faith', q: 'youth sports league website', label: 'Youth Sports Leagues' },
  { cat: 'Nonprofit, Community & Faith', q: 'alumni association website', label: 'Alumni Associations' },
  { cat: 'Nonprofit, Community & Faith', q: 'trade association website', label: 'Trade Associations' },
  { cat: 'Nonprofit, Community & Faith', q: 'chamber of commerce website', label: 'Chambers of Commerce' },
  { cat: 'Nonprofit, Community & Faith', q: 'environmental green ngo website', label: 'Environmental NGOs' },
  { cat: 'Nonprofit, Community & Faith', q: 'arts culture council website', label: 'Arts Councils' },
  { cat: 'Nonprofit, Community & Faith', q: 'food bank pantry website', label: 'Food Banks' },
  { cat: 'Nonprofit, Community & Faith', q: 'homeless shelter website', label: 'Homeless Shelters' },
  { cat: 'Nonprofit, Community & Faith', q: 'veterans support ngo website', label: 'Veterans Nonprofits' },
  { cat: 'Nonprofit, Community & Faith', q: 'disability advocacy website', label: 'Advocacy Groups' },
  { cat: 'Nonprofit, Community & Faith', q: 'mental health nonprofit website', label: 'Mental Health NGOs' },
  { cat: 'Nonprofit, Community & Faith', q: 'scholarship fund website', label: 'Scholarship Funds' },
  { cat: 'Nonprofit, Community & Faith', q: 'museum historical society website', label: 'Museums' },
  { cat: 'Nonprofit, Community & Faith', q: 'botanical garden website', label: 'Botanical Gardens' },
  { cat: 'Nonprofit, Community & Faith', q: 'zoo aquarium website design', label: 'Zoos & Aquariums' },
  { cat: 'Nonprofit, Community & Faith', q: 'performing arts center website', label: 'Performing Arts Centers' },
  { cat: 'Nonprofit, Community & Faith', q: 'rotary kiwanis club website', label: 'Service Clubs' },
  { cat: 'Nonprofit, Community & Faith', q: 'fraternal lodge website', label: 'Fraternal Lodges' },
  { cat: 'Nonprofit, Community & Faith', q: 'volunteer coordination website', label: 'Volunteer Organizations' },
  { cat: 'Nonprofit, Community & Faith', q: 'humanitarian relief website', label: 'Humanitarian Relief' },

  // 17. Financial & Insurance (25)
  { cat: 'Financial & Insurance', q: 'insurance agency website design', label: 'Insurance Agencies' },
  { cat: 'Financial & Insurance', q: 'independent insurance broker website', label: 'Insurance Brokers' },
  { cat: 'Financial & Insurance', q: 'auto insurance agency website', label: 'Auto Insurance Brokers' },
  { cat: 'Financial & Insurance', q: 'health insurance broker website', label: 'Health Insurance Brokers' },
  { cat: 'Financial & Insurance', q: 'life insurance agent website', label: 'Life Insurance Agents' },
  { cat: 'Financial & Insurance', q: 'commercial insurance website', label: 'Commercial Insurance' },
  { cat: 'Financial & Insurance', q: 'credit union bank website', label: 'Credit Unions' },
  { cat: 'Financial & Insurance', q: 'mortgage brokerage website', label: 'Mortgage Brokerages' },
  { cat: 'Financial & Insurance', q: 'loan agency website design', label: 'Lending Agencies' },
  { cat: 'Financial & Insurance', q: 'debt relief consolidation website', label: 'Debt Relief Firms' },
  { cat: 'Financial & Insurance', q: 'credit repair company website', label: 'Credit Repair Services' },
  { cat: 'Financial & Insurance', q: 'investment firm website design', label: 'Investment Firms' },
  { cat: 'Financial & Insurance', q: 'venture capital firm website', label: 'Venture Capital Firms' },
  { cat: 'Financial & Insurance', q: 'angel investor syndicate website', label: 'Angel Syndicates' },
  { cat: 'Financial & Insurance', q: 'private equity firm website', label: 'Private Equity Firms' },
  { cat: 'Financial & Insurance', q: 'hedge fund website design', label: 'Hedge Funds' },
  { cat: 'Financial & Insurance', q: 'wealth management advisor website', label: 'Wealth Advisors' },
  { cat: 'Financial & Insurance', q: 'estate planning financial website', label: 'Estate Financial Planners' },
  { cat: 'Financial & Insurance', q: 'retirement planner website', label: 'Retirement Planners' },
  { cat: 'Financial & Insurance', q: 'payroll service company website', label: 'Payroll Providers' },
  { cat: 'Financial & Insurance', q: 'factoring merchant advance website', label: 'Merchant Advance Providers' },
  { cat: 'Financial & Insurance', q: 'commercial lending firm website', label: 'Commercial Lenders' },
  { cat: 'Financial & Insurance', q: 'crypto wealth advisor website', label: 'Crypto Advisors' },
  { cat: 'Financial & Insurance', q: 'tax strategy firm website', label: 'Tax Strategists' },
  { cat: 'Financial & Insurance', q: 'audit compliance firm website', label: 'Audit Firms' },

  // 18. Home Services & Improvement (25)
  { cat: 'Home Services & Improvement', q: 'plumber plumbing contractor website', label: 'Plumbers' },
  { cat: 'Home Services & Improvement', q: 'electrician electrical contractor website', label: 'Electricians' },
  { cat: 'Home Services & Improvement', q: 'hvac heating cooling website', label: 'HVAC Companies' },
  { cat: 'Home Services & Improvement', q: 'roofing company website design', label: 'Roofing Contractors' },
  { cat: 'Home Services & Improvement', q: 'pest control exterminator website', label: 'Pest Control Services' },
  { cat: 'Home Services & Improvement', q: 'landscaping lawn care website', label: 'Landscapers' },
  { cat: 'Home Services & Improvement', q: 'tree removal arborist website', label: 'Arborists' },
  { cat: 'Home Services & Improvement', q: 'garage door installer website', label: 'Garage Door Installers' },
  { cat: 'Home Services & Improvement', q: 'window replacement website', label: 'Window Replacement' },
  { cat: 'Home Services & Improvement', q: 'siding contractor website', label: 'Siding Contractors' },
  { cat: 'Home Services & Improvement', q: 'gutter installation website', label: 'Gutter Installers' },
  { cat: 'Home Services & Improvement', q: 'water heater repair website', label: 'Water Heater Technicians' },
  { cat: 'Home Services & Improvement', q: 'solar energy installer website', label: 'Solar Installers' },
  { cat: 'Home Services & Improvement', q: 'pool cleaning maintenance website', label: 'Pool Technicians' },
  { cat: 'Home Services & Improvement', q: 'handyman repair service website', label: 'Handyman Services' },
  { cat: 'Home Services & Improvement', q: 'appliance repair technician website', label: 'Appliance Repair' },
  { cat: 'Home Services & Improvement', q: 'locksmith emergency website', label: 'Emergency Locksmiths' },
  { cat: 'Home Services & Improvement', q: 'house painter painting website', label: 'House Painters' },
  { cat: 'Home Services & Improvement', q: 'flooring carpet installer website', label: 'Flooring Installers' },
  { cat: 'Home Services & Improvement', q: 'tile stone contractor website', label: 'Tile & Stone Masons' },
  { cat: 'Home Services & Improvement', q: 'cabinet maker website design', label: 'Cabinet Makers' },
  { cat: 'Home Services & Improvement', q: 'countertop installer website', label: 'Countertop Installers' },
  { cat: 'Home Services & Improvement', q: 'water damage restoration website', label: 'Water Damage Restoration' },
  { cat: 'Home Services & Improvement', q: 'mold removal inspector website', label: 'Mold Inspectors' },
  { cat: 'Home Services & Improvement', q: 'septic drain cleaning website', label: 'Drain Cleaners' },

  // 19. B2B Agencies & Marketing (25)
  { cat: 'B2B Agencies & Marketing', q: 'digital marketing agency website', label: 'Marketing Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'seo agency website design', label: 'SEO Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'ppc ad agency website', label: 'PPC Ad Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'social media agency website', label: 'Social Media Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'content marketing agency website', label: 'Content Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'public relations pr agency website', label: 'PR Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'branding agency website design', label: 'Branding Studios' },
  { cat: 'B2B Agencies & Marketing', q: 'web design agency website', label: 'Web Design Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'graphic design studio website', label: 'Design Studios' },
  { cat: 'B2B Agencies & Marketing', q: 'video production agency website', label: 'Video Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'influencer marketing agency website', label: 'Influencer Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'copywriting agency website', label: 'Copywriting Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'email marketing agency website', label: 'Email Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'conversion rate optimization agency', label: 'CRO Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'amazon ecommerce agency website', label: 'Amazon Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'app development agency website', label: 'App Studios' },
  { cat: 'B2B Agencies & Marketing', q: 'software development studio website', label: 'Software Studios' },
  { cat: 'B2B Agencies & Marketing', q: 'ai agency automation website', label: 'AI Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'growth hacking agency website', label: 'Growth Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'lead generation agency website', label: 'Lead Gen Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'sales enablement agency website', label: 'Sales Enablement' },
  { cat: 'B2B Agencies & Marketing', q: 'b2b consulting firm website', label: 'B2B Consulting Firms' },
  { cat: 'B2B Agencies & Marketing', q: 'outbound sales agency website', label: 'Outbound Agencies' },
  { cat: 'B2B Agencies & Marketing', q: 'fractional cmo agency website', label: 'Fractional CMOs' },
  { cat: 'B2B Agencies & Marketing', q: 'creative ad studio website', label: 'Creative Ad Studios' },

  // 20. Niche & Specialty Services (25)
  { cat: 'Niche & Specialty Services', q: 'pet groomer mobile website', label: 'Mobile Pet Groomers' },
  { cat: 'Niche & Specialty Services', q: 'dog trainer behaviorist website', label: 'Dog Trainers' },
  { cat: 'Niche & Specialty Services', q: 'equestrian horse boarding website', label: 'Horse Boarding Stables' },
  { cat: 'Niche & Specialty Services', q: 'gun range firearms website', label: 'Gun Ranges' },
  { cat: 'Niche & Specialty Services', q: 'scuba diving charter website', label: 'Scuba Diving Charters' },
  { cat: 'Niche & Specialty Services', q: 'surf school charter website', label: 'Surf Schools' },
  { cat: 'Niche & Specialty Services', q: 'ski snowboard rental website', label: 'Ski & Snowboard Rentals' },
  { cat: 'Niche & Specialty Services', q: 'golf course country club website', label: 'Golf & Country Clubs' },
  { cat: 'Niche & Specialty Services', q: 'bowling alley venue website', label: 'Bowling Centers' },
  { cat: 'Niche & Specialty Services', q: 'marina boat charter website', label: 'Boat Charters' },
  { cat: 'Niche & Specialty Services', q: 'tattoo removal clinic website', label: 'Tattoo Removal Clinics' },
  { cat: 'Niche & Specialty Services', q: 'cryotherapy center website', label: 'Cryotherapy Centers' },
  { cat: 'Niche & Specialty Services', q: 'float tank spa website', label: 'Float Tank Spas' },
  { cat: 'Niche & Specialty Services', q: 'sauna cold plunge studio website', label: 'Sauna & Plunge Studios' },
  { cat: 'Niche & Specialty Services', q: 'astrology tarot reader website', label: 'Astrology & Tarot Readers' },
  { cat: 'Niche & Specialty Services', q: 'hypnotherapist clinic website', label: 'Hypnotherapists' },
  { cat: 'Niche & Specialty Services', q: 'reiki energy healer website', label: 'Energy Healers' },
  { cat: 'Niche & Specialty Services', q: 'naturopathic doctor website', label: 'Naturopathic Doctors' },
  { cat: 'Niche & Specialty Services', q: 'functional medicine clinic website', label: 'Functional Medicine' },
  { cat: 'Niche & Specialty Services', q: 'iv hydration clinic website', label: 'IV Hydration Bars' },
  { cat: 'Niche & Specialty Services', q: 'biohacking wellness lab website', label: 'Biohacking Labs' },
  { cat: 'Niche & Specialty Services', q: 'mobile detailer car wash website', label: 'Mobile Auto Detailers' },
  { cat: 'Niche & Specialty Services', q: 'car storage facility website', label: 'Car Storage Facilities' },
  { cat: 'Niche & Specialty Services', q: 'art restoration studio website', label: 'Art Restorers' },
  { cat: 'Niche & Specialty Services', q: 'antique dealer shop website', label: 'Antique Dealers' }
];

// Capitalize helper
const capitalize = (str) => str.replace(/\b\w/g, l => l.toUpperCase());

// Generate 500 clean page objects
export const LONG_TAIL_PAGES = RAW_QUERIES.map((item, index) => {
  const slug = slugify(item.q);
  const path = `/${slug}`;
  const titleQuery = capitalize(item.q);

  return {
    id: `lt-${index + 1}`,
    slug,
    path,
    targetKeyword: item.q,
    category: item.cat,
    label: item.label,
    title: `${titleQuery}: High-Converting Custom Web Design | LaunchGremlin`,
    description: `Looking for the ${item.q}? LaunchGremlin engineers sub-second custom websites built for high lead conversion, 100/100 Core Web Vitals performance, and local search dominance.`,
    keywords: `${item.q}, custom ${item.label.toLowerCase()} website, ${item.q} cost, best ${item.q} builder, local SEO for ${item.label.toLowerCase()}`,
    canonical: `${SITE_DOMAIN}${path}`,
    heroBadge: `HIGH-CONVERTING WEB DESIGN FOR ${item.label.toUpperCase()}`,
    heroHeadline: `HIGH-PERFORMANCE WEBSITES FOR ${item.label.toUpperCase()}.`,
    heroSubheadline: `Transform your online presence. Sub-second load speeds, automated lead capture funnels, and top Google rankings built specifically for ${item.label.toLowerCase()}.`,
    ctaText: `Build ${item.label} Site`,
    benefits: [
      {
        title: `Instant ${item.label} Lead Funnel`,
        desc: `Frictionless inquiry forms, appointment scheduling widgets, and 1-click customer contact triggers tailored for ${item.label.toLowerCase()}.`,
        tag: 'LEAD CAPTURE'
      },
      {
        title: `Sub-Second Load Latency (0.24s)`,
        desc: `Outrank competitors on Google search with 100/100 Core Web Vitals scores built on React 18 and edge CDN infrastructure.`,
        tag: 'LIGHTNING SPEED'
      },
      {
        title: `Automated Local SEO & Schema`,
        desc: `Rank at the top of local search results with automated Organization, Service, FAQPage, and LocalBusiness JSON-LD markup.`,
        tag: 'SEARCH DOMINANCE'
      },
      {
        title: `Visual Portfolio & Service Showcase`,
        desc: `High-resolution image galleries, before-and-after comparisons, and social proof displays optimized for mobile screen devices.`,
        tag: 'CONVERSION UX'
      }
    ],
    whyLaunchGremlin: [
      `Engineered specifically for ${item.label.toLowerCase()} seeking high-ticket client acquisition`,
      `Delivered in 7 to 10 business days with optional 72-Hour MVP sprint guarantee`,
      `Sub-second page speeds so prospective clients never bounce or leave`,
      `Integrated with your existing CRM, scheduling software, and payment portals`
    ],
    faqs: [
      {
        question: `Why choose LaunchGremlin for a ${item.label.toLowerCase()} website over generic templates?`,
        answer: `Generic website builders load slowly, lack custom database integrations, and fail Core Web Vitals audits. LaunchGremlin builds custom React 18 applications engineered for sub-second speed, high lead conversion rates, and automated SEO rankings.`
      },
      {
        question: `How long does it take to design and launch a new ${item.label.toLowerCase()} website?`,
        answer: `Our standard custom websites launch in 7 to 10 business days. For urgent deadlines, we offer a 72-Hour MVP rapid launch option.`
      },
      {
        question: `Will the website be optimized for mobile smartphones and local Google searches?`,
        answer: `Yes! Over 80% of local searches occur on mobile devices. Every site we build is engineered mobile-first with 44px touch targets and complete local schema markup.`
      }
    ]
  };
});

export function getLongTailBySlug(slug) {
  return LONG_TAIL_PAGES.find(p => p.slug === slug);
}

export function getLongTailByCategory(category) {
  return LONG_TAIL_PAGES.filter(p => p.category === category);
}
