/**
 * Subtitle Generator Utility (.SRT and .VTT formats)
 * Converts talking clip scenes with word-count pacing into timed subtitle files.
 */

// Helper to format seconds into SRT timestamp (00:00:00,000)
function formatSrtTimestamp(seconds) {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);

  return (
    String(hrs).padStart(2, '0') +
    ':' +
    String(mins).padStart(2, '0') +
    ':' +
    String(secs).padStart(2, '0') +
    ',' +
    String(millis).padStart(3, '0')
  );
}

// Helper to format seconds into WebVTT timestamp (00:00:00.000)
function formatVttTimestamp(seconds) {
  return formatSrtTimestamp(seconds).replace(',', '.');
}

/**
 * Generates .SRT (SubRip) subtitle string from talking clip scenes
 */
export function generateSrtContent(scenes = [], estTotalDuration = 45) {
  if (!scenes || scenes.length === 0) return '';

  // Calculate proportional durations based on spoken text length
  const totalWords = scenes.reduce((acc, sc) => acc + (sc.audio_spoken?.split(/\s+/).length || 1), 0);
  const speakingRate = Math.max(totalWords / estTotalDuration, 2.2); // ~2.2-3 words per second

  let currentTime = 0;
  const srtBlocks = [];

  scenes.forEach((sc, idx) => {
    const text = sc.audio_spoken || '';
    const wordsCount = text.split(/\s+/).length || 5;
    const duration = Math.max(wordsCount / speakingRate, 3.5);
    const startTime = currentTime;
    const endTime = startTime + duration;
    currentTime = endTime + 0.3; // brief 300ms pause

    const block = [
      idx + 1,
      `${formatSrtTimestamp(startTime)} --> ${formatSrtTimestamp(endTime)}`,
      text.trim()
    ].join('\n');

    srtBlocks.push(block);
  });

  return srtBlocks.join('\n\n') + '\n';
}

/**
 * Generates .VTT (WebVTT) subtitle string from talking clip scenes
 */
export function generateVttContent(scenes = [], estTotalDuration = 45) {
  if (!scenes || scenes.length === 0) return 'WEBVTT\n\n';

  const totalWords = scenes.reduce((acc, sc) => acc + (sc.audio_spoken?.split(/\s+/).length || 1), 0);
  const speakingRate = Math.max(totalWords / estTotalDuration, 2.2);

  let currentTime = 0;
  const vttBlocks = ['WEBVTT - Generated by LaunchGremlin Content Engine\n'];

  scenes.forEach((sc, idx) => {
    const text = sc.audio_spoken || '';
    const wordsCount = text.split(/\s+/).length || 5;
    const duration = Math.max(wordsCount / speakingRate, 3.5);
    const startTime = currentTime;
    const endTime = startTime + duration;
    currentTime = endTime + 0.3;

    const block = [
      `cue-${idx + 1}`,
      `${formatVttTimestamp(startTime)} --> ${formatVttTimestamp(endTime)}`,
      text.trim()
    ].join('\n');

    vttBlocks.push(block);
  });

  return vttBlocks.join('\n\n') + '\n';
}

/**
 * Trigger download of subtitle file in browser
 */
export function downloadSubtitleFile(content, filename = 'video_captions', extension = 'srt') {
  const mimeType = extension === 'vtt' ? 'text/vtt;charset=utf-8;' : 'application/x-subrip;charset=utf-8;';
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.${extension}`;
  link.click();
}
